baseURL = "https://truecheck.io"
title = "TrueCheck"
languageCode = "en-us"
paginate = 10
enableRobotsTXT = true

[params]
  description = "TrueCheck is a simple KYC verification dashboard to streamline compliance with seamless customer onboarding, realtime verification and robust security features"