baseURL = "https://truecheck.io"
title = "TrueCheck"
languageCode = "en-us"
paginate = 10
enableRobotsTXT = true

[params]
  description = "TrueCheck is the simplest AML compliance solution for businesses, with detailed AML scans and simple case management"